### PR TITLE
fix changing the upload field title

### PR DESCRIPTION
**Pull request by eduardovilke**
#### What problem is this solving?

Give context to the title of the upload field

### CODE REVIEW

**Comment by eduardovilke** [comment]
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [x]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

**Comment by eduardovilke** [comment]
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [x]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

**Comment by eduardovilke** [comment]
@klzns Everything okay around here? Or do I need to change something else?

**Review by icazevedo — APPROVED** [review]
LGTM

**Review by camilavcoutinho — APPROVED** [review]
LGTM

**Pull request closed without merging**
